name: Update README.md

on:
  workflow_call:
    inputs:
      schema:
        type: string
        required: true
      version:
        type: string
        required: true
      id:
        type: string
        required: true
        description: 'GitHub private package registry ID'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update ${{ env.name }} version badge in README.md
        shell: bash
        run: |
          BADGE_TEMPLATE="[![Generic badge](https://img.shields.io/badge/${{ env.name }}-%s-blue.svg)](https://github.com/navikt/aap-avro/packages/${{ env.github_package_id }}?version=%s)"
          BADGE=$(printf "$BADGE_TEMPLATE" "${{ env.semver }}" "${{ env.semver }}")
          sed -i -e "s|.*${{ env.name }}-.*-blue.svg.*|$BADGE|g" README.md

          EXAMPLE_TEMPLATE="implementation(\"no.nav.aap.avro:${{ env.name }}:%s\")"
          EXAMPLE=$(printf "$EXAMPLE_TEMPLATE" "${{ env.semver }}")
          sed -i -e "s|implementation.*${{ env.name }}.*|$EXAMPLE|g" README.md

          git add README.md
          git commit -m "Update version badges"
          git pull --rebase
          git push --force-with-lease
